/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend.JDialogEdificios;

import ipc12023.juegopokemon_proyecto2.backend.JuegoPokemonException;
import ipc12023.juegopokemon_proyecto2.backend.Jugador;
import ipc12023.juegopokemon_proyecto2.frontend.JuegoPokemonApp;
import ipc12023.juegopokemon_proyecto2.backend.articulosTienda.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class JDlgTienda extends javax.swing.JDialog {
    
    
    Jugador jugador;
    JuegoPokemonApp ventana;

    /**
     * Creates new form JDlgTienda
     */
    public JDlgTienda(java.awt.Frame parent, boolean modal, Jugador jugador, JuegoPokemonApp ventana) {
        super(parent, modal);
        this.jugador = jugador;
        this.ventana = ventana;
        initComponents();
        
        jLblNombre.setText(this.jugador.getNombre());
        actualizarOroJugador();
        super.setLocation(500, 200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDsktpPnPrincipal = new javax.swing.JDesktopPane();
        jPnlMenuCatchball = new javax.swing.JPanel();
        jLblCatchball = new javax.swing.JLabel();
        jLblPrecioCatchball = new javax.swing.JLabel();
        jButtonCNormal = new javax.swing.JButton();
        jPnlPrecioCtNormal = new javax.swing.JPanel();
        jLblPrecioCtNormal = new javax.swing.JLabel();
        jButtonCtSemiprofesinal = new javax.swing.JButton();
        jPnlPrecioCtSemiprofesional = new javax.swing.JPanel();
        jLblPrecioCtSemiprofesional = new javax.swing.JLabel();
        jButtonCtProfesional = new javax.swing.JButton();
        jPnlPrecioCtProfesional = new javax.swing.JPanel();
        jLblPrecioCtProfesional = new javax.swing.JLabel();
        jLblLimSup = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jPnlMenuPocion = new javax.swing.JPanel();
        jLblPocion = new javax.swing.JLabel();
        jLblPrecioPocion = new javax.swing.JLabel();
        jButtonPSuave = new javax.swing.JButton();
        jPnlPrecioPSuave = new javax.swing.JPanel();
        jLblPrecioPSuave = new javax.swing.JLabel();
        jButtonPFuerte = new javax.swing.JButton();
        jPnlPrecioPFuerte = new javax.swing.JPanel();
        jLblPrecioPFuerte = new javax.swing.JLabel();
        jPnlOroJugador = new javax.swing.JPanel();
        jLblTextoOroDisponible = new javax.swing.JLabel();
        jLblOroJugador = new javax.swing.JLabel();
        jLblImagenTendero = new javax.swing.JLabel();
        jPnlDatos = new javax.swing.JPanel();
        jLblTNombre = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTBienvendida = new javax.swing.JLabel();
        jLblTInstrucciones = new javax.swing.JLabel();
        jLblLimInf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TIENDA");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 255, 204));
        setFocusCycleRoot(false);
        setFocusable(false);
        setName("dialogTienda"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jDsktpPnPrincipal.setBackground(new java.awt.Color(204, 255, 204));

        jPnlMenuCatchball.setBackground(new java.awt.Color(255, 153, 0));
        jPnlMenuCatchball.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnlMenuCatchball.setLayout(new java.awt.GridLayout(4, 2));

        jLblCatchball.setForeground(new java.awt.Color(0, 0, 0));
        jLblCatchball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cathball.png"))); // NOI18N
        jLblCatchball.setText("     Catchball");
        jLblCatchball.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnlMenuCatchball.add(jLblCatchball);

        jLblPrecioCatchball.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioCatchball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/oro.png"))); // NOI18N
        jLblPrecioCatchball.setText("       Precio");
        jLblPrecioCatchball.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnlMenuCatchball.add(jLblPrecioCatchball);

        jButtonCNormal.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCNormal.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCNormal.setText("Normal");
        jButtonCNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCNormalActionPerformed(evt);
            }
        });
        jPnlMenuCatchball.add(jButtonCNormal);

        jPnlPrecioCtNormal.setBackground(new java.awt.Color(204, 204, 255));

        jLblPrecioCtNormal.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioCtNormal.setText("          2 monedas");
        jLblPrecioCtNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPnlPrecioCtNormalLayout = new javax.swing.GroupLayout(jPnlPrecioCtNormal);
        jPnlPrecioCtNormal.setLayout(jPnlPrecioCtNormalLayout);
        jPnlPrecioCtNormalLayout.setHorizontalGroup(
            jPnlPrecioCtNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPnlPrecioCtNormalLayout.setVerticalGroup(
            jPnlPrecioCtNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlMenuCatchball.add(jPnlPrecioCtNormal);

        jButtonCtSemiprofesinal.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCtSemiprofesinal.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCtSemiprofesinal.setText("Semiprofesional");
        jButtonCtSemiprofesinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCtSemiprofesinalActionPerformed(evt);
            }
        });
        jPnlMenuCatchball.add(jButtonCtSemiprofesinal);

        jPnlPrecioCtSemiprofesional.setBackground(new java.awt.Color(204, 204, 255));

        jLblPrecioCtSemiprofesional.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioCtSemiprofesional.setText("          5 monedas");
        jLblPrecioCtSemiprofesional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPnlPrecioCtSemiprofesionalLayout = new javax.swing.GroupLayout(jPnlPrecioCtSemiprofesional);
        jPnlPrecioCtSemiprofesional.setLayout(jPnlPrecioCtSemiprofesionalLayout);
        jPnlPrecioCtSemiprofesionalLayout.setHorizontalGroup(
            jPnlPrecioCtSemiprofesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtSemiprofesional, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPnlPrecioCtSemiprofesionalLayout.setVerticalGroup(
            jPnlPrecioCtSemiprofesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtSemiprofesional, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlMenuCatchball.add(jPnlPrecioCtSemiprofesional);

        jButtonCtProfesional.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCtProfesional.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCtProfesional.setText("Profesional");
        jButtonCtProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCtProfesionalActionPerformed(evt);
            }
        });
        jPnlMenuCatchball.add(jButtonCtProfesional);

        jPnlPrecioCtProfesional.setBackground(new java.awt.Color(204, 204, 255));

        jLblPrecioCtProfesional.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioCtProfesional.setText("         10 monedas");
        jLblPrecioCtProfesional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPnlPrecioCtProfesionalLayout = new javax.swing.GroupLayout(jPnlPrecioCtProfesional);
        jPnlPrecioCtProfesional.setLayout(jPnlPrecioCtProfesionalLayout);
        jPnlPrecioCtProfesionalLayout.setHorizontalGroup(
            jPnlPrecioCtProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPnlPrecioCtProfesionalLayout.setVerticalGroup(
            jPnlPrecioCtProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioCtProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlMenuCatchball.add(jPnlPrecioCtProfesional);

        jLblLimSup.setText("##");

        jButtonSalir.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPnlMenuPocion.setBackground(new java.awt.Color(255, 153, 0));
        jPnlMenuPocion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnlMenuPocion.setLayout(new java.awt.GridLayout(3, 2));

        jLblPocion.setForeground(new java.awt.Color(0, 0, 0));
        jLblPocion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pocion.png"))); // NOI18N
        jLblPocion.setText("    Pocion");
        jLblPocion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnlMenuPocion.add(jLblPocion);

        jLblPrecioPocion.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioPocion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/oro.png"))); // NOI18N
        jLblPrecioPocion.setText("    Precio");
        jLblPrecioPocion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnlMenuPocion.add(jLblPrecioPocion);

        jButtonPSuave.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPSuave.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPSuave.setText("Suave");
        jButtonPSuave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPSuaveActionPerformed(evt);
            }
        });
        jPnlMenuPocion.add(jButtonPSuave);

        jPnlPrecioPSuave.setBackground(new java.awt.Color(204, 204, 255));

        jLblPrecioPSuave.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioPSuave.setText("      20 monedas");
        jLblPrecioPSuave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPnlPrecioPSuaveLayout = new javax.swing.GroupLayout(jPnlPrecioPSuave);
        jPnlPrecioPSuave.setLayout(jPnlPrecioPSuaveLayout);
        jPnlPrecioPSuaveLayout.setHorizontalGroup(
            jPnlPrecioPSuaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioPSuave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPnlPrecioPSuaveLayout.setVerticalGroup(
            jPnlPrecioPSuaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioPSuave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlMenuPocion.add(jPnlPrecioPSuave);

        jButtonPFuerte.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPFuerte.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPFuerte.setText("Fuerte");
        jButtonPFuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFuerteActionPerformed(evt);
            }
        });
        jPnlMenuPocion.add(jButtonPFuerte);

        jPnlPrecioPFuerte.setBackground(new java.awt.Color(204, 204, 255));

        jLblPrecioPFuerte.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecioPFuerte.setText("     100 monedas");
        jLblPrecioPFuerte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPnlPrecioPFuerteLayout = new javax.swing.GroupLayout(jPnlPrecioPFuerte);
        jPnlPrecioPFuerte.setLayout(jPnlPrecioPFuerteLayout);
        jPnlPrecioPFuerteLayout.setHorizontalGroup(
            jPnlPrecioPFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioPFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPnlPrecioPFuerteLayout.setVerticalGroup(
            jPnlPrecioPFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrecioPFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlMenuPocion.add(jPnlPrecioPFuerte);

        jPnlOroJugador.setBackground(new java.awt.Color(204, 255, 204));

        jLblTextoOroDisponible.setForeground(new java.awt.Color(0, 0, 0));
        jLblTextoOroDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/oro.png"))); // NOI18N
        jLblTextoOroDisponible.setText("ORO DISPONIBLE:");
        jPnlOroJugador.add(jLblTextoOroDisponible);

        jLblOroJugador.setForeground(new java.awt.Color(0, 0, 0));
        jLblOroJugador.setText("0000.00");
        jPnlOroJugador.add(jLblOroJugador);

        jLblImagenTendero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tendero.png"))); // NOI18N

        jPnlDatos.setBackground(new java.awt.Color(255, 255, 255));

        jLblTNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNombre.setText("Hola ");

        jLblNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblNombre.setText("nombre");

        jLblTBienvendida.setForeground(new java.awt.Color(0, 0, 0));
        jLblTBienvendida.setText("Bienvenido a la tienda");

        jLblTInstrucciones.setForeground(new java.awt.Color(0, 0, 0));
        jLblTInstrucciones.setText("Presiona un artículo para comprarlo");

        javax.swing.GroupLayout jPnlDatosLayout = new javax.swing.GroupLayout(jPnlDatos);
        jPnlDatos.setLayout(jPnlDatosLayout);
        jPnlDatosLayout.setHorizontalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosLayout.createSequentialGroup()
                        .addComponent(jLblTNombre)
                        .addGap(6, 6, 6)
                        .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblTBienvendida)
                    .addComponent(jLblTInstrucciones)))
        );
        jPnlDatosLayout.setVerticalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTNombre)
                    .addComponent(jLblNombre))
                .addGap(6, 6, 6)
                .addComponent(jLblTBienvendida)
                .addGap(6, 6, 6)
                .addComponent(jLblTInstrucciones))
        );

        jLblLimInf.setText("##");

        jDsktpPnPrincipal.setLayer(jPnlMenuCatchball, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jLblLimSup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jButtonSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jPnlMenuPocion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jPnlOroJugador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jLblImagenTendero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jPnlDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jLblLimInf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDsktpPnPrincipalLayout = new javax.swing.GroupLayout(jDsktpPnPrincipal);
        jDsktpPnPrincipal.setLayout(jDsktpPnPrincipalLayout);
        jDsktpPnPrincipalLayout.setHorizontalGroup(
            jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlOroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPnlMenuPocion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jPnlMenuCatchball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLblLimSup))
            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                .addComponent(jLblLimInf)
                .addGap(6, 6, 6)
                .addComponent(jLblImagenTendero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jButtonSalir))
        );
        jDsktpPnPrincipalLayout.setVerticalGroup(
            jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblLimSup)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                                .addComponent(jPnlOroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPnlMenuPocion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPnlMenuCatchball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLblLimInf))
                    .addComponent(jLblImagenTendero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonSalir))))
        );

        getContentPane().add(jDsktpPnPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCtSemiprofesinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCtSemiprofesinalActionPerformed
        // TODO add your handling code here:
        try {
            jugador.gastarOro(CatchballSemiprofesional.PRECIO, ventana);
            jugador.añadirAInventario(new CatchballSemiprofesional());
            actualizarOroJugador();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCtSemiprofesinalActionPerformed

    private void jButtonPFuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFuerteActionPerformed
        // TODO add your handling code here:
        try {
            jugador.gastarOro(PocionFuerte.PRECIO, ventana);
            jugador.añadirAInventario(new PocionFuerte());
            actualizarOroJugador();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPFuerteActionPerformed

    private void jButtonPSuaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPSuaveActionPerformed
       
        try {
            jugador.gastarOro(PocionSuave.PRECIO, ventana);
            jugador.añadirAInventario(new PocionSuave());
            actualizarOroJugador();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPSuaveActionPerformed

    private void jButtonCNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCNormalActionPerformed
        // TODO add your handling code here:
        try {
            jugador.gastarOro(CatchballNormal.PRECIO, ventana);
            jugador.añadirAInventario(new CatchballNormal());
            actualizarOroJugador();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCNormalActionPerformed

    private void jButtonCtProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCtProfesionalActionPerformed
        // TODO add your handling code here:
        try {
            jugador.gastarOro(CatchballProfesional.PRECIO, ventana);
            jugador.añadirAInventario(new CatchballProfesional());
            actualizarOroJugador();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCtProfesionalActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void actualizarOroJugador (){
        jLblOroJugador.setText(String.valueOf(jugador.getOro()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCNormal;
    private javax.swing.JButton jButtonCtProfesional;
    private javax.swing.JButton jButtonCtSemiprofesinal;
    private javax.swing.JButton jButtonPFuerte;
    private javax.swing.JButton jButtonPSuave;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JDesktopPane jDsktpPnPrincipal;
    private javax.swing.JLabel jLblCatchball;
    private javax.swing.JLabel jLblImagenTendero;
    private javax.swing.JLabel jLblLimInf;
    private javax.swing.JLabel jLblLimSup;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblOroJugador;
    private javax.swing.JLabel jLblPocion;
    private javax.swing.JLabel jLblPrecioCatchball;
    private javax.swing.JLabel jLblPrecioCtNormal;
    private javax.swing.JLabel jLblPrecioCtProfesional;
    private javax.swing.JLabel jLblPrecioCtSemiprofesional;
    private javax.swing.JLabel jLblPrecioPFuerte;
    private javax.swing.JLabel jLblPrecioPSuave;
    private javax.swing.JLabel jLblPrecioPocion;
    private javax.swing.JLabel jLblTBienvendida;
    private javax.swing.JLabel jLblTInstrucciones;
    private javax.swing.JLabel jLblTNombre;
    private javax.swing.JLabel jLblTextoOroDisponible;
    private javax.swing.JPanel jPnlDatos;
    private javax.swing.JPanel jPnlMenuCatchball;
    private javax.swing.JPanel jPnlMenuPocion;
    private javax.swing.JPanel jPnlOroJugador;
    private javax.swing.JPanel jPnlPrecioCtNormal;
    private javax.swing.JPanel jPnlPrecioCtProfesional;
    private javax.swing.JPanel jPnlPrecioCtSemiprofesional;
    private javax.swing.JPanel jPnlPrecioPFuerte;
    private javax.swing.JPanel jPnlPrecioPSuave;
    // End of variables declaration//GEN-END:variables
}
