/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend.JDialogEdificios;

import ipc12023.juegopokemon_proyecto2.frontend.*;
import ipc12023.juegopokemon_proyecto2.backend.*;
import ipc12023.juegopokemon_proyecto2.frontend.pokemon.Pokemon;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class JDlgHospital extends javax.swing.JDialog {
    
    private static final int PRECIO_HOSPITAL = 50;
    
    Jugador jugador;
    Pokemon pokemonHerido;
    JuegoPokemonApp ventana;

    /**
     * Creates new form JDlg
     */
    public JDlgHospital(java.awt.Frame parent, boolean modal, Jugador jugador, JuegoPokemonApp ventana) {
        
        super(parent, modal);
        this.jugador = jugador;
        this.ventana = ventana;
        initComponents();
        jLblNombre.setText(this.jugador.getNombre());
        super.setLocation(500, 250);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlHospital = new javax.swing.JPanel();
        jLblImagenEnfermera = new javax.swing.JLabel();
        jPnlTexto = new javax.swing.JPanel();
        jLblPrecio = new javax.swing.JLabel();
        jLblHola = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblBienvenida = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonPokemonesHeridos = new javax.swing.JButton();
        jLblLimIf = new javax.swing.JLabel();
        jLblLimIf1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HOSPITAL");
        setBounds(new java.awt.Rectangle(125, 125, 0, 0));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPnlHospital.setBackground(new java.awt.Color(204, 204, 255));

        jLblImagenEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N

        jPnlTexto.setBackground(new java.awt.Color(255, 255, 255));

        jLblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLblPrecio.setText("Precio por sanar a un pokemon: 50 Monedas");

        jLblHola.setForeground(new java.awt.Color(0, 0, 0));
        jLblHola.setText("Hola");

        jLblNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblNombre.setText("nombre");

        jLblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        jLblBienvenida.setText("Bienvenido al Hospital de Pokemones");

        javax.swing.GroupLayout jPnlTextoLayout = new javax.swing.GroupLayout(jPnlTexto);
        jPnlTexto.setLayout(jPnlTextoLayout);
        jPnlTextoLayout.setHorizontalGroup(
            jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTextoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBienvenida)
                    .addGroup(jPnlTextoLayout.createSequentialGroup()
                        .addComponent(jLblHola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblNombre))
                    .addComponent(jLblPrecio))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPnlTextoLayout.setVerticalGroup(
            jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblHola)
                    .addComponent(jLblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPrecio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalir.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonPokemonesHeridos.setBackground(new java.awt.Color(255, 153, 0));
        jButtonPokemonesHeridos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPokemonesHeridos.setText("Pokemones Heridos");
        jButtonPokemonesHeridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokemonesHeridosActionPerformed(evt);
            }
        });

        jLblLimIf.setText("###");

        jLblLimIf1.setText("###");

        javax.swing.GroupLayout jPnlHospitalLayout = new javax.swing.GroupLayout(jPnlHospital);
        jPnlHospital.setLayout(jPnlHospitalLayout);
        jPnlHospitalLayout.setHorizontalGroup(
            jPnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHospitalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLblImagenEnfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlHospitalLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLblLimIf))
                    .addGroup(jPnlHospitalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonPokemonesHeridos)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir))
                    .addGroup(jPnlHospitalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPnlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLblLimIf1)
        );
        jPnlHospitalLayout.setVerticalGroup(
            jPnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHospitalLayout.createSequentialGroup()
                .addGroup(jPnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlHospitalLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLblImagenEnfermera))
                    .addGroup(jPnlHospitalLayout.createSequentialGroup()
                        .addComponent(jLblLimIf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPnlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPokemonesHeridos)
                            .addComponent(jButtonSalir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblLimIf1))
        );

        getContentPane().add(jPnlHospital);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        try {
            jugador.actualizar();
            this.dispose();
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonPokemonesHeridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokemonesHeridosActionPerformed
        
        Pokemon[] pokemonesHeridos = jugador.getPokemonesHeridos();
        // TAMAÑO DEL MENU
        
        if (pokemonesHeridos.length == 0) {
            JOptionPane.showMessageDialog(ventana, "No Tienes Pokemones Heridos");
        } else{
            int columna = AdminJuego.tamañoMenu(pokemonesHeridos.length)[AdminJuego.COLUMNA];
            int fila = AdminJuego.tamañoMenu(pokemonesHeridos.length)[AdminJuego.FILA];     
            JDlgMenuPokemon menu = new JDlgMenuPokemon(ventana, true, pokemonesHeridos, 1, "Elija un pokemon para sanarlo", columna, fila);
            menu.setVisible(true);
            pokemonHerido = menu.getPokemonesElegidos()[0];
            
            if (pokemonHerido != null) {
                sanar(pokemonHerido);
            } 
        }
           
         
    }//GEN-LAST:event_jButtonPokemonesHeridosActionPerformed

    private void sanar(Pokemon pokemonHerido){
        try {
            jugador.gastarOro(PRECIO_HOSPITAL, ventana);
            pokemonHerido.sanarPokemon();
            jugador.actualizar();
            JOptionPane.showMessageDialog(ventana, pokemonHerido.getNombre() + " ha reuperado sus puntos de salud", "", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (JuegoPokemonException e) {
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
//    public void setLocationMove(int moveWidth, int moveHeight) {
//        // Obtenemos el tamaño de la pantalla.
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        // Obtenemos el tamaño de nuestro frame.
//        Dimension frameSize = this.getSize();
//        frameSize.width = frameSize.width > screenSize.width?screenSize.width:frameSize.width;
//        frameSize.height = frameSize.height > screenSize.height?screenSize.height:frameSize.height;   
//        // We define the location. Definimos la localización.
//        setLocation((screenSize.width - frameSize.width) / 2 + moveWidth, (screenSize.height - frameSize.height) / 2 + moveHeight);        
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokemonesHeridos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLblBienvenida;
    private javax.swing.JLabel jLblHola;
    private javax.swing.JLabel jLblImagenEnfermera;
    private javax.swing.JLabel jLblLimIf;
    private javax.swing.JLabel jLblLimIf1;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblPrecio;
    private javax.swing.JPanel jPnlHospital;
    private javax.swing.JPanel jPnlTexto;
    // End of variables declaration//GEN-END:variables
}
