/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend.JDialogEdificios;

/**
 *
 * @author Personal
 */
public class JDlgConfirmar extends javax.swing.JDialog {

    private boolean opcion;
    /**
     * Creates new form JDlgConfirmar
     */
    public JDlgConfirmar(java.awt.Frame parent, boolean modal, String enunciado, String title) {
        super(parent, modal);
        initComponents();
        jLblEnunciado.setText(enunciado);
        this.setTitle(title);
        super.setLocation(500, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlTexto = new javax.swing.JPanel();
        jLblEnunciado = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jButtonAceptar = new javax.swing.JButton();
        jButtomSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPnlTexto.setBackground(new java.awt.Color(204, 204, 255));

        jLblEnunciado.setForeground(new java.awt.Color(0, 0, 0));
        jLblEnunciado.setText("Precio por la talar un arbol: 5");

        jButtonAceptar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(jButtonAceptar);

        jButtomSalir.setBackground(new java.awt.Color(255, 153, 0));
        jButtomSalir.setForeground(new java.awt.Color(51, 51, 51));
        jButtomSalir.setText("CANCELAR");
        jButtomSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomSalirActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(jButtomSalir);

        javax.swing.GroupLayout jPnlTextoLayout = new javax.swing.GroupLayout(jPnlTexto);
        jPnlTexto.setLayout(jPnlTextoLayout);
        jPnlTextoLayout.setHorizontalGroup(
            jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTextoLayout.createSequentialGroup()
                .addGroup(jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTextoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlTextoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPnlTextoLayout.setVerticalGroup(
            jPnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTextoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlTexto);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
          opcion = true;
          super.hide();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtomSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomSalirActionPerformed
        opcion = false;
        super.hide();
    }//GEN-LAST:event_jButtomSalirActionPerformed

    public boolean getOpcion(){
        return opcion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtomSalir;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLblEnunciado;
    private javax.swing.JPanel jPnlTexto;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
