/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend.JDialogEdificios;

import ipc12023.juegopokemon_proyecto2.backend.Jugador;
import ipc12023.juegopokemon_proyecto2.frontend.*;
import ipc12023.juegopokemon_proyecto2.frontend.pokemon.Pokemon;

/**
 *
 * @author Personal
 */
public class JDlgEdIventario extends javax.swing.JDialog {
    
    private Jugador jugador;

    /**
     * Creates new form JDlgEdIventario
     */
    public JDlgEdIventario(java.awt.Frame parent, boolean modal, Jugador jugador, JuegoPokemonApp ventana) {
        super(parent, modal);
        this.jugador = jugador;
        initComponents();
        cargarDatos();
    }

    private void cargarDatos (){
        
        jLblNombre.setText(jugador.getNombre());
        jLblNivelJugador.setText(String.valueOf(jugador.getNivel()));
        jLblOroJugador.setText(String.valueOf(jugador.getOro()));
        //catchballs disponibles
        jLblCtNormales.setText(String.valueOf(jugador.getCatchballlsNormalesDisponibles()));
        jLblCtSemiprofesionales.setText(String.valueOf(jugador.getCatchballlsSemiprofesionalesDisponibles()));
        jLblCtProfesionales.setText(String.valueOf(jugador.getCatchballlsProfesionalesDisponibles()));
        //pociones disponibles
        jLblPcSuave.setText(String.valueOf(jugador.getPocionesSuavesDisponibles()));
        jLblPcFuerte.setText(String.valueOf(jugador.getPocionesFuertesDisponibles()));
        //Agregar informacion de los pokemones
        Pokemon[] pokemones = jugador.getPokemones();
        for (int i = 0; i < pokemones.length; i++) {
            if (pokemones[i] != null) {
                cargarDatosPokemon(i, pokemones[i]);
            }
            
        }
    }
    
    private void cargarDatosPokemon(int noPokemon, Pokemon pokemon){
        
        
        
        switch (noPokemon) {
            
            case 0:
                pokemon.agregarImagenYMarco();
                jPnlImagenPokemon0.removeAll();
                jPnlImagenPokemon0.add(pokemon);
                jPnlImagenPokemon0.repaint();
                jPnlImagenPokemon0.revalidate();
                jLblVidaBase0.setText(String.valueOf(pokemon.getVidaBase()));
                jLblTipo0.setText(pokemon.getTipo());
                jLblNivel0.setText(String.valueOf(pokemon.getNivel()));
                break;
             case 1:
                pokemon.agregarImagenYMarco();
               
                jPnlImagenPokemon1.removeAll();
                jPnlImagenPokemon1.add(pokemon);
                jPnlImagenPokemon1.repaint();
                jPnlImagenPokemon1.revalidate();
                
                jLblVidaBase1.setText(String.valueOf(pokemon.getVidaBase()));
                jLblTipo1.setText(pokemon.getTipo());
                jLblNivel1.setText(String.valueOf(pokemon.getNivel()));
                break;
             case 2:
                pokemon.agregarImagenYMarco();
                jPnlImagenPokemon2.removeAll();
                jPnlImagenPokemon2.add(pokemon);
                jPnlImagenPokemon2.repaint();
                jPnlImagenPokemon2.revalidate();
                jLblVidaBase2.setText(String.valueOf(pokemon.getVidaBase()));
                jLblTipo2.setText(pokemon.getTipo());
                jLblNivel2.setText(String.valueOf(pokemon.getNivel()));
                break;
             case 3:
                pokemon.agregarImagenYMarco();
                jPnlImagenPokemon3.removeAll();
                jPnlImagenPokemon3.add(pokemon);
                jPnlImagenPokemon3.repaint();
                jPnlImagenPokemon3.revalidate();
                jLblVidaBase3.setText(String.valueOf(pokemon.getVidaBase()));
                jLblTipo3.setText(pokemon.getTipo());
                jLblNivel3.setText( String.valueOf(pokemon.getNivel()));
                break;
             case 4:
                pokemon.agregarImagenYMarco();
                jPnlImagenPokemon4.removeAll();
                jPnlImagenPokemon4.add(pokemon);
                jPnlImagenPokemon4.repaint();
                jPnlImagenPokemon4.revalidate();
                jLblVidaBase4.setText( String.valueOf(pokemon.getVidaBase()) );
                jLblTipo4.setText(pokemon.getTipo());
                jLblNivel4.setText(String.valueOf(pokemon.getNivel()));
                break;
            default:
                throw new AssertionError();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDsktpPnVentanaIventarioJugador = new javax.swing.JDesktopPane();
        jPnlContenedorPociones = new javax.swing.JPanel();
        jPnlCatchballs1 = new javax.swing.JPanel();
        jLblPociones = new javax.swing.JLabel();
        jLblCantidadPociones = new javax.swing.JLabel();
        jLblTxPcSuave = new javax.swing.JLabel();
        jLblPcSuave = new javax.swing.JLabel();
        jLblTxPcFuerte = new javax.swing.JLabel();
        jLblPcFuerte = new javax.swing.JLabel();
        jPnlContenedorCatcballs = new javax.swing.JPanel();
        jPnlCatchballs = new javax.swing.JPanel();
        jLbl = new javax.swing.JLabel();
        jLblCantidadCatchballs = new javax.swing.JLabel();
        jLblTxCtNormal = new javax.swing.JLabel();
        jLblCtNormales = new javax.swing.JLabel();
        jLblTxCtSemiprofesional = new javax.swing.JLabel();
        jLblCtSemiprofesionales = new javax.swing.JLabel();
        jLblTxCtProfesional = new javax.swing.JLabel();
        jLblCtProfesionales = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jIntrnlFrmInventarioPokemones = new javax.swing.JInternalFrame();
        jPnlCartaPokemon0 = new javax.swing.JPanel();
        jPnlIfPokemon0 = new javax.swing.JPanel();
        jLblTVidaBase0 = new javax.swing.JLabel();
        jLblVidaBase0 = new javax.swing.JLabel();
        jLblTTipo0 = new javax.swing.JLabel();
        jLblTipo0 = new javax.swing.JLabel();
        jLblTNivel0 = new javax.swing.JLabel();
        jLblNivel0 = new javax.swing.JLabel();
        jPnlImagenPokemon0 = new javax.swing.JPanel();
        jLblPokemon0 = new javax.swing.JLabel();
        jPnlCartaPokemon1 = new javax.swing.JPanel();
        jPnlIfPokemon1 = new javax.swing.JPanel();
        jLblTVidaBase1 = new javax.swing.JLabel();
        jLblVidaBase1 = new javax.swing.JLabel();
        jLblTTipo1 = new javax.swing.JLabel();
        jLblTipo1 = new javax.swing.JLabel();
        jLblTNivel1 = new javax.swing.JLabel();
        jLblNivel1 = new javax.swing.JLabel();
        jPnlPokemon1 = new javax.swing.JPanel();
        jPnlImagenPokemon1 = new javax.swing.JPanel();
        jLblPokemon1 = new javax.swing.JLabel();
        jPnlCartaPokemon2 = new javax.swing.JPanel();
        jPnlIfPokemon2 = new javax.swing.JPanel();
        jLblTVidaBase2 = new javax.swing.JLabel();
        jLblVidaBase2 = new javax.swing.JLabel();
        jLblTTipo2 = new javax.swing.JLabel();
        jLblTipo2 = new javax.swing.JLabel();
        jLblTNivel2 = new javax.swing.JLabel();
        jLblNivel2 = new javax.swing.JLabel();
        jPnlImagenPokemon2 = new javax.swing.JPanel();
        jPnlPokemon9 = new javax.swing.JPanel();
        jLblPokemon2 = new javax.swing.JLabel();
        jPnlCartaPokemon4 = new javax.swing.JPanel();
        jPnlIfPokemon4 = new javax.swing.JPanel();
        jLblTVidaBase4 = new javax.swing.JLabel();
        jLblVidaBase4 = new javax.swing.JLabel();
        jLblTTipo4 = new javax.swing.JLabel();
        jLblTipo4 = new javax.swing.JLabel();
        jLblTNivel4 = new javax.swing.JLabel();
        jLblNivel4 = new javax.swing.JLabel();
        jPnlImagenPokemon4 = new javax.swing.JPanel();
        jLblPokemon4 = new javax.swing.JLabel();
        jPnlCartaPokemon3 = new javax.swing.JPanel();
        jPnlIfPokemon3 = new javax.swing.JPanel();
        jLblTVidaBase3 = new javax.swing.JLabel();
        jLblVidaBase3 = new javax.swing.JLabel();
        jLblTTipo3 = new javax.swing.JLabel();
        jLblTipo3 = new javax.swing.JLabel();
        jLblTNivel3 = new javax.swing.JLabel();
        jLblNivel3 = new javax.swing.JLabel();
        jPnlImagenPokemon3 = new javax.swing.JPanel();
        jLblPokemon3 = new javax.swing.JLabel();
        jPnlMarcoDatosJugador = new javax.swing.JPanel();
        jPnlDatos = new javax.swing.JPanel();
        jLblImagenJugador = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTxNivel = new javax.swing.JLabel();
        jLblNivelJugador = new javax.swing.JLabel();
        jLblTxOro = new javax.swing.JLabel();
        jLblOroJugador = new javax.swing.JLabel();
        jLblLimInf = new javax.swing.JLabel();
        jLblLlimSup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INVENTARIO");
        setBackground(new java.awt.Color(204, 255, 204));
        setSize(new java.awt.Dimension(790, 150));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jDsktpPnVentanaIventarioJugador.setBackground(new java.awt.Color(255, 255, 204));

        jPnlContenedorPociones.setBackground(new java.awt.Color(255, 153, 0));

        jPnlCatchballs1.setBackground(new java.awt.Color(204, 204, 255));
        jPnlCatchballs1.setLayout(new java.awt.GridBagLayout());

        jLblPociones.setForeground(new java.awt.Color(0, 0, 0));
        jLblPociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pocion.png"))); // NOI18N
        jLblPociones.setText("Pocion");
        jPnlCatchballs1.add(jLblPociones, new java.awt.GridBagConstraints());

        jLblCantidadPociones.setForeground(new java.awt.Color(0, 0, 0));
        jLblCantidadPociones.setText("   Cantidad  ");
        jPnlCatchballs1.add(jLblCantidadPociones, new java.awt.GridBagConstraints());

        jLblTxPcSuave.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxPcSuave.setText("  Suave :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPnlCatchballs1.add(jLblTxPcSuave, gridBagConstraints);

        jLblPcSuave.setForeground(new java.awt.Color(0, 0, 0));
        jLblPcSuave.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPnlCatchballs1.add(jLblPcSuave, gridBagConstraints);

        jLblTxPcFuerte.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxPcFuerte.setText(" Fuerte:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPnlCatchballs1.add(jLblTxPcFuerte, gridBagConstraints);

        jLblPcFuerte.setForeground(new java.awt.Color(0, 0, 0));
        jLblPcFuerte.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPnlCatchballs1.add(jLblPcFuerte, gridBagConstraints);

        jPnlContenedorPociones.add(jPnlCatchballs1);

        jPnlContenedorCatcballs.setBackground(new java.awt.Color(255, 153, 0));

        jPnlCatchballs.setBackground(new java.awt.Color(204, 204, 255));
        jPnlCatchballs.setLayout(new java.awt.GridBagLayout());

        jLbl.setForeground(new java.awt.Color(0, 0, 0));
        jLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cathball.png"))); // NOI18N
        jLbl.setText("Catchballs");
        jPnlCatchballs.add(jLbl, new java.awt.GridBagConstraints());

        jLblCantidadCatchballs.setForeground(new java.awt.Color(0, 0, 0));
        jLblCantidadCatchballs.setText(" Cantidad    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPnlCatchballs.add(jLblCantidadCatchballs, gridBagConstraints);

        jLblTxCtNormal.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxCtNormal.setText(" Normales :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPnlCatchballs.add(jLblTxCtNormal, gridBagConstraints);

        jLblCtNormales.setForeground(new java.awt.Color(0, 0, 0));
        jLblCtNormales.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        jPnlCatchballs.add(jLblCtNormales, gridBagConstraints);

        jLblTxCtSemiprofesional.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxCtSemiprofesional.setText(" Semiprofesionales:    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPnlCatchballs.add(jLblTxCtSemiprofesional, gridBagConstraints);

        jLblCtSemiprofesionales.setForeground(new java.awt.Color(0, 0, 0));
        jLblCtSemiprofesionales.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPnlCatchballs.add(jLblCtSemiprofesionales, gridBagConstraints);

        jLblTxCtProfesional.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxCtProfesional.setText("Profesionales:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPnlCatchballs.add(jLblTxCtProfesional, gridBagConstraints);

        jLblCtProfesionales.setForeground(new java.awt.Color(0, 0, 0));
        jLblCtProfesionales.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        jPnlCatchballs.add(jLblCtProfesionales, gridBagConstraints);

        jPnlContenedorCatcballs.add(jPnlCatchballs);

        jButtonSalir.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setName("Inventario de Pokemones"); // NOI18N

        jIntrnlFrmInventarioPokemones.setBackground(new java.awt.Color(255, 255, 204));
        jIntrnlFrmInventarioPokemones.setTitle("Inventario de Pokemones");
        jIntrnlFrmInventarioPokemones.setEnabled(false);
        jIntrnlFrmInventarioPokemones.setFocusCycleRoot(false);
        jIntrnlFrmInventarioPokemones.setVisible(true);

        jPnlCartaPokemon0.setBackground(new java.awt.Color(204, 204, 255));

        jPnlIfPokemon0.setBackground(new java.awt.Color(204, 204, 255));
        jPnlIfPokemon0.setLayout(new java.awt.GridLayout(3, 2));

        jLblTVidaBase0.setForeground(new java.awt.Color(0, 0, 0));
        jLblTVidaBase0.setText("Vida Base:");
        jPnlIfPokemon0.add(jLblTVidaBase0);

        jLblVidaBase0.setForeground(new java.awt.Color(0, 0, 0));
        jLblVidaBase0.setText("000.00");
        jPnlIfPokemon0.add(jLblVidaBase0);

        jLblTTipo0.setForeground(new java.awt.Color(0, 0, 0));
        jLblTTipo0.setText("Tipo:");
        jPnlIfPokemon0.add(jLblTTipo0);

        jLblTipo0.setForeground(new java.awt.Color(0, 0, 0));
        jLblTipo0.setText("000.00");
        jPnlIfPokemon0.add(jLblTipo0);

        jLblTNivel0.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNivel0.setText("Nivel:");
        jPnlIfPokemon0.add(jLblTNivel0);

        jLblNivel0.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivel0.setText("000.00");
        jPnlIfPokemon0.add(jLblNivel0);

        jPnlImagenPokemon0.setBackground(new java.awt.Color(204, 255, 204));

        jLblPokemon0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon/disponible.png"))); // NOI18N
        jPnlImagenPokemon0.add(jLblPokemon0);

        javax.swing.GroupLayout jPnlCartaPokemon0Layout = new javax.swing.GroupLayout(jPnlCartaPokemon0);
        jPnlCartaPokemon0.setLayout(jPnlCartaPokemon0Layout);
        jPnlCartaPokemon0Layout.setHorizontalGroup(
            jPnlCartaPokemon0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlImagenPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPnlCartaPokemon0Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPnlIfPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlCartaPokemon0Layout.setVerticalGroup(
            jPnlCartaPokemon0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon0Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlImagenPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPnlIfPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlCartaPokemon1.setBackground(new java.awt.Color(204, 204, 255));

        jPnlIfPokemon1.setBackground(new java.awt.Color(204, 204, 255));
        jPnlIfPokemon1.setLayout(new java.awt.GridLayout(3, 2));

        jLblTVidaBase1.setForeground(new java.awt.Color(0, 0, 0));
        jLblTVidaBase1.setText("Vida Base:");
        jPnlIfPokemon1.add(jLblTVidaBase1);

        jLblVidaBase1.setForeground(new java.awt.Color(0, 0, 0));
        jLblVidaBase1.setText("000.00");
        jPnlIfPokemon1.add(jLblVidaBase1);

        jLblTTipo1.setForeground(new java.awt.Color(0, 0, 0));
        jLblTTipo1.setText("Tipo:");
        jPnlIfPokemon1.add(jLblTTipo1);

        jLblTipo1.setForeground(new java.awt.Color(0, 0, 0));
        jLblTipo1.setText("000.00");
        jPnlIfPokemon1.add(jLblTipo1);

        jLblTNivel1.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNivel1.setText("Nivel:");
        jPnlIfPokemon1.add(jLblTNivel1);

        jLblNivel1.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivel1.setText("000.00");
        jPnlIfPokemon1.add(jLblNivel1);

        jPnlPokemon1.setBackground(new java.awt.Color(204, 204, 255));

        jPnlImagenPokemon1.setBackground(new java.awt.Color(204, 255, 204));

        jLblPokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon/disponible.png"))); // NOI18N
        jPnlImagenPokemon1.add(jLblPokemon1);

        javax.swing.GroupLayout jPnlPokemon1Layout = new javax.swing.GroupLayout(jPnlPokemon1);
        jPnlPokemon1.setLayout(jPnlPokemon1Layout);
        jPnlPokemon1Layout.setHorizontalGroup(
            jPnlPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlPokemon1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPnlImagenPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlPokemon1Layout.setVerticalGroup(
            jPnlPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPokemon1Layout.createSequentialGroup()
                .addComponent(jPnlImagenPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlCartaPokemon1Layout = new javax.swing.GroupLayout(jPnlCartaPokemon1);
        jPnlCartaPokemon1.setLayout(jPnlCartaPokemon1Layout);
        jPnlCartaPokemon1Layout.setHorizontalGroup(
            jPnlCartaPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPnlCartaPokemon1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPnlIfPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlCartaPokemon1Layout.setVerticalGroup(
            jPnlCartaPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlIfPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlCartaPokemon2.setBackground(new java.awt.Color(204, 204, 255));

        jPnlIfPokemon2.setBackground(new java.awt.Color(204, 204, 255));
        jPnlIfPokemon2.setLayout(new java.awt.GridLayout(3, 2));

        jLblTVidaBase2.setForeground(new java.awt.Color(0, 0, 0));
        jLblTVidaBase2.setText("Vida Base:");
        jPnlIfPokemon2.add(jLblTVidaBase2);

        jLblVidaBase2.setForeground(new java.awt.Color(0, 0, 0));
        jLblVidaBase2.setText("000.00");
        jPnlIfPokemon2.add(jLblVidaBase2);

        jLblTTipo2.setForeground(new java.awt.Color(0, 0, 0));
        jLblTTipo2.setText("Tipo:");
        jPnlIfPokemon2.add(jLblTTipo2);

        jLblTipo2.setForeground(new java.awt.Color(0, 0, 0));
        jLblTipo2.setText("000.00");
        jPnlIfPokemon2.add(jLblTipo2);

        jLblTNivel2.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNivel2.setText("Nivel:");
        jPnlIfPokemon2.add(jLblTNivel2);

        jLblNivel2.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivel2.setText("000.00");
        jPnlIfPokemon2.add(jLblNivel2);

        jPnlImagenPokemon2.setBackground(new java.awt.Color(204, 255, 204));

        jPnlPokemon9.setBackground(new java.awt.Color(204, 255, 204));
        jPnlPokemon9.setLayout(new javax.swing.OverlayLayout(jPnlPokemon9));

        jLblPokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon/disponible.png"))); // NOI18N
        jPnlPokemon9.add(jLblPokemon2);

        jPnlImagenPokemon2.add(jPnlPokemon9);

        javax.swing.GroupLayout jPnlCartaPokemon2Layout = new javax.swing.GroupLayout(jPnlCartaPokemon2);
        jPnlCartaPokemon2.setLayout(jPnlCartaPokemon2Layout);
        jPnlCartaPokemon2Layout.setHorizontalGroup(
            jPnlCartaPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlImagenPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPnlCartaPokemon2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPnlIfPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlCartaPokemon2Layout.setVerticalGroup(
            jPnlCartaPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlImagenPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlIfPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlCartaPokemon4.setBackground(new java.awt.Color(204, 204, 255));

        jPnlIfPokemon4.setBackground(new java.awt.Color(204, 204, 255));
        jPnlIfPokemon4.setLayout(new java.awt.GridLayout(3, 2));

        jLblTVidaBase4.setForeground(new java.awt.Color(0, 0, 0));
        jLblTVidaBase4.setText("Vida Base:");
        jPnlIfPokemon4.add(jLblTVidaBase4);

        jLblVidaBase4.setForeground(new java.awt.Color(0, 0, 0));
        jLblVidaBase4.setText("000.00");
        jPnlIfPokemon4.add(jLblVidaBase4);

        jLblTTipo4.setForeground(new java.awt.Color(0, 0, 0));
        jLblTTipo4.setText("Tipo:");
        jPnlIfPokemon4.add(jLblTTipo4);

        jLblTipo4.setForeground(new java.awt.Color(0, 0, 0));
        jLblTipo4.setText("000.00");
        jPnlIfPokemon4.add(jLblTipo4);

        jLblTNivel4.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNivel4.setText("Nivel:");
        jPnlIfPokemon4.add(jLblTNivel4);

        jLblNivel4.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivel4.setText("000.00");
        jPnlIfPokemon4.add(jLblNivel4);

        jPnlImagenPokemon4.setBackground(new java.awt.Color(204, 255, 204));

        jLblPokemon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon/disponible.png"))); // NOI18N
        jPnlImagenPokemon4.add(jLblPokemon4);

        javax.swing.GroupLayout jPnlCartaPokemon4Layout = new javax.swing.GroupLayout(jPnlCartaPokemon4);
        jPnlCartaPokemon4.setLayout(jPnlCartaPokemon4Layout);
        jPnlCartaPokemon4Layout.setHorizontalGroup(
            jPnlCartaPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlImagenPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPnlCartaPokemon4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPnlIfPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlCartaPokemon4Layout.setVerticalGroup(
            jPnlCartaPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlImagenPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlIfPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlCartaPokemon3.setBackground(new java.awt.Color(204, 204, 255));

        jPnlIfPokemon3.setBackground(new java.awt.Color(204, 204, 255));
        jPnlIfPokemon3.setLayout(new java.awt.GridLayout(3, 2));

        jLblTVidaBase3.setForeground(new java.awt.Color(0, 0, 0));
        jLblTVidaBase3.setText("Vida Base:");
        jPnlIfPokemon3.add(jLblTVidaBase3);

        jLblVidaBase3.setForeground(new java.awt.Color(0, 0, 0));
        jLblVidaBase3.setText("000.00");
        jPnlIfPokemon3.add(jLblVidaBase3);

        jLblTTipo3.setForeground(new java.awt.Color(0, 0, 0));
        jLblTTipo3.setText("Tipo:");
        jPnlIfPokemon3.add(jLblTTipo3);

        jLblTipo3.setForeground(new java.awt.Color(0, 0, 0));
        jLblTipo3.setText("000.00");
        jPnlIfPokemon3.add(jLblTipo3);

        jLblTNivel3.setForeground(new java.awt.Color(0, 0, 0));
        jLblTNivel3.setText("Nivel:");
        jPnlIfPokemon3.add(jLblTNivel3);

        jLblNivel3.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivel3.setText("000.00");
        jPnlIfPokemon3.add(jLblNivel3);

        jPnlImagenPokemon3.setBackground(new java.awt.Color(204, 255, 204));

        jLblPokemon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon/disponible.png"))); // NOI18N
        jPnlImagenPokemon3.add(jLblPokemon3);

        javax.swing.GroupLayout jPnlCartaPokemon3Layout = new javax.swing.GroupLayout(jPnlCartaPokemon3);
        jPnlCartaPokemon3.setLayout(jPnlCartaPokemon3Layout);
        jPnlCartaPokemon3Layout.setHorizontalGroup(
            jPnlCartaPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlImagenPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPnlCartaPokemon3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPnlIfPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlCartaPokemon3Layout.setVerticalGroup(
            jPnlCartaPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCartaPokemon3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlImagenPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlIfPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jIntrnlFrmInventarioPokemonesLayout = new javax.swing.GroupLayout(jIntrnlFrmInventarioPokemones.getContentPane());
        jIntrnlFrmInventarioPokemones.getContentPane().setLayout(jIntrnlFrmInventarioPokemonesLayout);
        jIntrnlFrmInventarioPokemonesLayout.setHorizontalGroup(
            jIntrnlFrmInventarioPokemonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntrnlFrmInventarioPokemonesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPnlCartaPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlCartaPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPnlCartaPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlCartaPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPnlCartaPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jIntrnlFrmInventarioPokemonesLayout.setVerticalGroup(
            jIntrnlFrmInventarioPokemonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntrnlFrmInventarioPokemonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jIntrnlFrmInventarioPokemonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlCartaPokemon0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCartaPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCartaPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCartaPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCartaPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jIntrnlFrmInventarioPokemones);

        jPnlMarcoDatosJugador.setBackground(new java.awt.Color(255, 153, 0));

        jPnlDatos.setBackground(new java.awt.Color(204, 204, 255));

        jLblImagenJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casillas/jugador.png"))); // NOI18N

        jLblNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblNombre.setText("nombre");

        jLblTxNivel.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxNivel.setText("Nivel:");

        jLblNivelJugador.setForeground(new java.awt.Color(0, 0, 0));
        jLblNivelJugador.setText("00:");

        jLblTxOro.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxOro.setText("Oro:");

        jLblOroJugador.setForeground(new java.awt.Color(0, 0, 0));
        jLblOroJugador.setText("00:");

        javax.swing.GroupLayout jPnlDatosLayout = new javax.swing.GroupLayout(jPnlDatos);
        jPnlDatos.setLayout(jPnlDatosLayout);
        jPnlDatosLayout.setHorizontalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosLayout.createSequentialGroup()
                        .addComponent(jLblImagenJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTxNivel)
                            .addComponent(jLblTxOro))
                        .addGap(10, 10, 10)
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNivelJugador)
                            .addComponent(jLblOroJugador)))))
        );
        jPnlDatosLayout.setVerticalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLblNombre)
                .addGap(4, 4, 4)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblImagenJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlDatosLayout.createSequentialGroup()
                                .addComponent(jLblTxNivel)
                                .addGap(4, 4, 4)
                                .addComponent(jLblTxOro))
                            .addGroup(jPnlDatosLayout.createSequentialGroup()
                                .addComponent(jLblNivelJugador)
                                .addGap(4, 4, 4)
                                .addComponent(jLblOroJugador))))))
        );

        jPnlMarcoDatosJugador.add(jPnlDatos);

        jLblLimInf.setText("##");

        jLblLlimSup.setText("##");

        jDsktpPnVentanaIventarioJugador.setLayer(jPnlContenedorPociones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jPnlContenedorCatcballs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jButtonSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jPnlMarcoDatosJugador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jLblLimInf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnVentanaIventarioJugador.setLayer(jLblLlimSup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDsktpPnVentanaIventarioJugadorLayout = new javax.swing.GroupLayout(jDsktpPnVentanaIventarioJugador);
        jDsktpPnVentanaIventarioJugador.setLayout(jDsktpPnVentanaIventarioJugadorLayout);
        jDsktpPnVentanaIventarioJugadorLayout.setHorizontalGroup(
            jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPnlMarcoDatosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPnlContenedorCatcballs, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jPnlContenedorPociones, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonSalir)))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblLlimSup))
                    .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblLimInf)))
                .addContainerGap())
        );
        jDsktpPnVentanaIventarioJugadorLayout.setVerticalGroup(
            jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPnlMarcoDatosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPnlContenedorCatcballs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPnlContenedorPociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonSalir))
                    .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jDsktpPnVentanaIventarioJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblLlimSup)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblLimInf)
                .addContainerGap())
        );

        getContentPane().add(jDsktpPnVentanaIventarioJugador);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JDesktopPane jDsktpPnVentanaIventarioJugador;
    private javax.swing.JInternalFrame jIntrnlFrmInventarioPokemones;
    private javax.swing.JLabel jLbl;
    private javax.swing.JLabel jLblCantidadCatchballs;
    private javax.swing.JLabel jLblCantidadPociones;
    private javax.swing.JLabel jLblCtNormales;
    private javax.swing.JLabel jLblCtProfesionales;
    private javax.swing.JLabel jLblCtSemiprofesionales;
    private javax.swing.JLabel jLblImagenJugador;
    private javax.swing.JLabel jLblLimInf;
    private javax.swing.JLabel jLblLlimSup;
    private javax.swing.JLabel jLblNivel0;
    private javax.swing.JLabel jLblNivel1;
    private javax.swing.JLabel jLblNivel2;
    private javax.swing.JLabel jLblNivel3;
    private javax.swing.JLabel jLblNivel4;
    private javax.swing.JLabel jLblNivelJugador;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblOroJugador;
    private javax.swing.JLabel jLblPcFuerte;
    private javax.swing.JLabel jLblPcSuave;
    private javax.swing.JLabel jLblPociones;
    private javax.swing.JLabel jLblPokemon0;
    private javax.swing.JLabel jLblPokemon1;
    private javax.swing.JLabel jLblPokemon2;
    private javax.swing.JLabel jLblPokemon3;
    private javax.swing.JLabel jLblPokemon4;
    private javax.swing.JLabel jLblTNivel0;
    private javax.swing.JLabel jLblTNivel1;
    private javax.swing.JLabel jLblTNivel2;
    private javax.swing.JLabel jLblTNivel3;
    private javax.swing.JLabel jLblTNivel4;
    private javax.swing.JLabel jLblTTipo0;
    private javax.swing.JLabel jLblTTipo1;
    private javax.swing.JLabel jLblTTipo2;
    private javax.swing.JLabel jLblTTipo3;
    private javax.swing.JLabel jLblTTipo4;
    private javax.swing.JLabel jLblTVidaBase0;
    private javax.swing.JLabel jLblTVidaBase1;
    private javax.swing.JLabel jLblTVidaBase2;
    private javax.swing.JLabel jLblTVidaBase3;
    private javax.swing.JLabel jLblTVidaBase4;
    private javax.swing.JLabel jLblTipo0;
    private javax.swing.JLabel jLblTipo1;
    private javax.swing.JLabel jLblTipo2;
    private javax.swing.JLabel jLblTipo3;
    private javax.swing.JLabel jLblTipo4;
    private javax.swing.JLabel jLblTxCtNormal;
    private javax.swing.JLabel jLblTxCtProfesional;
    private javax.swing.JLabel jLblTxCtSemiprofesional;
    private javax.swing.JLabel jLblTxNivel;
    private javax.swing.JLabel jLblTxOro;
    private javax.swing.JLabel jLblTxPcFuerte;
    private javax.swing.JLabel jLblTxPcSuave;
    private javax.swing.JLabel jLblVidaBase0;
    private javax.swing.JLabel jLblVidaBase1;
    private javax.swing.JLabel jLblVidaBase2;
    private javax.swing.JLabel jLblVidaBase3;
    private javax.swing.JLabel jLblVidaBase4;
    private javax.swing.JPanel jPnlCartaPokemon0;
    private javax.swing.JPanel jPnlCartaPokemon1;
    private javax.swing.JPanel jPnlCartaPokemon2;
    private javax.swing.JPanel jPnlCartaPokemon3;
    private javax.swing.JPanel jPnlCartaPokemon4;
    private javax.swing.JPanel jPnlCatchballs;
    private javax.swing.JPanel jPnlCatchballs1;
    private javax.swing.JPanel jPnlContenedorCatcballs;
    private javax.swing.JPanel jPnlContenedorPociones;
    private javax.swing.JPanel jPnlDatos;
    private javax.swing.JPanel jPnlIfPokemon0;
    private javax.swing.JPanel jPnlIfPokemon1;
    private javax.swing.JPanel jPnlIfPokemon2;
    private javax.swing.JPanel jPnlIfPokemon3;
    private javax.swing.JPanel jPnlIfPokemon4;
    private javax.swing.JPanel jPnlImagenPokemon0;
    private javax.swing.JPanel jPnlImagenPokemon1;
    private javax.swing.JPanel jPnlImagenPokemon2;
    private javax.swing.JPanel jPnlImagenPokemon3;
    private javax.swing.JPanel jPnlImagenPokemon4;
    private javax.swing.JPanel jPnlMarcoDatosJugador;
    private javax.swing.JPanel jPnlPokemon1;
    private javax.swing.JPanel jPnlPokemon9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
