/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend.JDialogEdificios;

import ipc12023.juegopokemon_proyecto2.backend.*;
import ipc12023.juegopokemon_proyecto2.frontend.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class JDlgMiniJuego extends javax.swing.JDialog {
    
    private final static int TAMANIO_NIVEL_PRINCIPIANTE = 10;
    private final static int TAMANIO_NIVEL_MEDIO = 8;
    private final static int TAMANIO_NIVEL_PROFESIONAL = 6;
    private final static int PASOS_NIVEL_PRINCIPIANTE = 100;
    private final static int PASOS_NIVEL_MEDIO = 50;
    private final static int PASOS_NIVEL_PROFESIONAL = 30;
    private final static int ORO_NIVEL_PRINCIPIANTE = 25;
    private final static int ORO_NIVEL_MEDIO = 50;
    private final static int ORO_NIVEL_PROFESIONAL = 75;
    private final static int PASOS_EXTRA_NIVEL_PRINCIPIANTE = 3;
    private final static int PASOS_EXTRA_NIVEL_MEDIO = 5;
    private final static int PASOS_EXTRA_NIVEL_PROFESIONAL = 10;
    
    private JuegoPokemonApp ventana;
    private Jugador jugador;
    

    /**
     * Creates new form JDlgMiniJuego
     */
    public JDlgMiniJuego(java.awt.Frame parent, boolean modal, Jugador jugador, JuegoPokemonApp ventana) {
        super(parent, modal);
        this.ventana = ventana;
        this.jugador = jugador;
        initComponents();
        jLblNombreJugador.setText(jugador.getNombre());
        this.setLocation(500, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDsktpPnPrincipal = new javax.swing.JDesktopPane();
        jBttnNivel1 = new javax.swing.JButton();
        jBttnNivel2 = new javax.swing.JButton();
        jBttnNivel3 = new javax.swing.JButton();
        jLblImagenCasinoGerente = new javax.swing.JLabel();
        jPnlBienvenida = new javax.swing.JPanel();
        jLblTxHola = new javax.swing.JLabel();
        jLblTxPedirNivel = new javax.swing.JLabel();
        jLblTxBienvenida = new javax.swing.JLabel();
        jLblNombreJugador = new javax.swing.JLabel();
        jBttnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jDsktpPnPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        jBttnNivel1.setBackground(new java.awt.Color(255, 153, 0));
        jBttnNivel1.setForeground(new java.awt.Color(0, 0, 0));
        jBttnNivel1.setText("Principiante");
        jBttnNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNivel1ActionPerformed(evt);
            }
        });

        jBttnNivel2.setBackground(new java.awt.Color(255, 153, 0));
        jBttnNivel2.setForeground(new java.awt.Color(0, 0, 0));
        jBttnNivel2.setText("Medio");
        jBttnNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNivel2ActionPerformed(evt);
            }
        });

        jBttnNivel3.setBackground(new java.awt.Color(255, 153, 0));
        jBttnNivel3.setForeground(new java.awt.Color(0, 0, 0));
        jBttnNivel3.setText("Profesional");
        jBttnNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNivel3ActionPerformed(evt);
            }
        });

        jLblImagenCasinoGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/casino.png"))); // NOI18N

        jPnlBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBienvenida.setForeground(new java.awt.Color(255, 255, 255));

        jLblTxHola.setBackground(new java.awt.Color(0, 0, 0));
        jLblTxHola.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxHola.setText("Hola");

        jLblTxPedirNivel.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxPedirNivel.setText("Escoje un nivel para jugar el mini juego");

        jLblTxBienvenida.setBackground(new java.awt.Color(0, 0, 0));
        jLblTxBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        jLblTxBienvenida.setText("Bienvenido al Casino");

        jLblNombreJugador.setBackground(new java.awt.Color(0, 0, 0));
        jLblNombreJugador.setForeground(new java.awt.Color(0, 0, 0));
        jLblNombreJugador.setText("NOMBRE");

        javax.swing.GroupLayout jPnlBienvenidaLayout = new javax.swing.GroupLayout(jPnlBienvenida);
        jPnlBienvenida.setLayout(jPnlBienvenidaLayout);
        jPnlBienvenidaLayout.setHorizontalGroup(
            jPnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBienvenidaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTxPedirNivel)
                    .addGroup(jPnlBienvenidaLayout.createSequentialGroup()
                        .addComponent(jLblTxHola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addComponent(jLblTxBienvenida))
                .addGap(18, 18, 18))
        );
        jPnlBienvenidaLayout.setVerticalGroup(
            jPnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTxHola)
                    .addComponent(jLblNombreJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTxBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTxPedirNivel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jBttnSalir.setBackground(new java.awt.Color(255, 153, 0));
        jBttnSalir.setForeground(new java.awt.Color(0, 0, 0));
        jBttnSalir.setText("SALIR");
        jBttnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSalirActionPerformed(evt);
            }
        });

        jDsktpPnPrincipal.setLayer(jBttnNivel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jBttnNivel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jBttnNivel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jLblImagenCasinoGerente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jPnlBienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDsktpPnPrincipal.setLayer(jBttnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDsktpPnPrincipalLayout = new javax.swing.GroupLayout(jDsktpPnPrincipal);
        jDsktpPnPrincipal.setLayout(jDsktpPnPrincipalLayout);
        jDsktpPnPrincipalLayout.setHorizontalGroup(
            jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addComponent(jLblImagenCasinoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBttnNivel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBttnNivel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBttnNivel3))
                            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBttnSalir)))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jDsktpPnPrincipalLayout.setVerticalGroup(
            jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPnlBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblImagenCasinoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDsktpPnPrincipalLayout.createSequentialGroup()
                        .addGroup(jDsktpPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBttnNivel1)
                            .addComponent(jBttnNivel2)
                            .addComponent(jBttnNivel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnSalir)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jDsktpPnPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNivel1ActionPerformed
        // TODO add your handling code here:
        crearNuevoMapaMiniJuego(TAMANIO_NIVEL_PRINCIPIANTE, PASOS_NIVEL_PRINCIPIANTE, PASOS_EXTRA_NIVEL_PRINCIPIANTE, ORO_NIVEL_PRINCIPIANTE);
    }//GEN-LAST:event_jBttnNivel1ActionPerformed

    private void jBttnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNivel2ActionPerformed
        // TODO add your handling code here:
        crearNuevoMapaMiniJuego(TAMANIO_NIVEL_MEDIO, PASOS_NIVEL_MEDIO, PASOS_EXTRA_NIVEL_MEDIO, ORO_NIVEL_MEDIO);
    }//GEN-LAST:event_jBttnNivel2ActionPerformed

    private void jBttnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNivel3ActionPerformed
        // TODO add your handling code here:
        crearNuevoMapaMiniJuego(TAMANIO_NIVEL_PROFESIONAL, PASOS_NIVEL_PROFESIONAL, PASOS_EXTRA_NIVEL_PROFESIONAL, ORO_NIVEL_PROFESIONAL);
    }//GEN-LAST:event_jBttnNivel3ActionPerformed

    private void jBttnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBttnSalirActionPerformed

    private void crearNuevoMapaMiniJuego(int tamaño, int pasos, int pasosExtra, int oro){
        
        try {
            MapaMiniJuego mapa = new MapaMiniJuego(jugador, ventana, tamaño, pasos, pasosExtra, oro);
            ventana.setMapa(mapa);
            ventana.refrescar();
            this.dispose();
        } catch (JuegoPokemonException e) {
           
            JOptionPane.showMessageDialog(ventana, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnNivel1;
    private javax.swing.JButton jBttnNivel2;
    private javax.swing.JButton jBttnNivel3;
    private javax.swing.JButton jBttnSalir;
    private javax.swing.JDesktopPane jDsktpPnPrincipal;
    private javax.swing.JLabel jLblImagenCasinoGerente;
    private javax.swing.JLabel jLblNombreJugador;
    private javax.swing.JLabel jLblTxBienvenida;
    private javax.swing.JLabel jLblTxHola;
    private javax.swing.JLabel jLblTxPedirNivel;
    private javax.swing.JPanel jPnlBienvenida;
    // End of variables declaration//GEN-END:variables
}
