
package ipc12023.juegopokemon_proyecto2.frontend;

import ipc12023.juegopokemon_proyecto2.backend.AdminJuego;
import ipc12023.juegopokemon_proyecto2.backend.JuegoPokemonException;
import ipc12023.juegopokemon_proyecto2.backend.Jugador;
import javax.swing.JOptionPane;

public class JDialogCargarPersonaje extends javax.swing.JDialog {

    private String contraseña;
    
    /**
     * Creates new form JDialogCargarPersonaje
     */
    public JDialogCargarPersonaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.setLocation(400, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblInstrucciones = new javax.swing.JLabel();
        jButtonCargar = new javax.swing.JButton();
        jPsswrdFld = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar Personaje");
        setBackground(new java.awt.Color(153, 153, 255));

        jLblInstrucciones.setForeground(new java.awt.Color(51, 51, 51));
        jLblInstrucciones.setText("Ingrese su contraseña");

        jButtonCargar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonCargar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCargar.setText("CARGAR");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCargar)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPsswrdFld))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblInstrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPsswrdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
       
        contraseña = null;
        
        try {
            
            contraseña = jPsswrdFld.getText();
            Jugador jugador = AdminJuego.cargar(contraseña);
            contraseña = jugador.getContraseña();
            super.setVisible(false);
            
        } catch (JuegoPokemonException e) {
            
            contraseña = null;
            jPsswrdFld.setText("");
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta intente de nuevo", "Contraseña Incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    public String getContraseña (){
        return contraseña;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JLabel jLblInstrucciones;
    private javax.swing.JPasswordField jPsswrdFld;
    // End of variables declaration//GEN-END:variables
}
