/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend;

import ipc12023.juegopokemon_proyecto2.backend.AdminJuego;
import ipc12023.juegopokemon_proyecto2.backend.JuegoPokemonException;
import ipc12023.juegopokemon_proyecto2.backend.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class JDialogNuevoPersonaje extends javax.swing.JDialog {
    
    private String contraseña;
    private String nombre;
    private JuegoPokemonApp ventana;
    /**
     * Creates new form JDialogNuevoPersonaje
     */
    public JDialogNuevoPersonaje(java.awt.Frame parent, boolean modal, JuegoPokemonApp ventana) {
        super(parent, modal);
        this.ventana = ventana;
        initComponents();
        super.setLocation(500, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBttnCrearPersonaje = new javax.swing.JButton();
        jTxtFldContraseña = new javax.swing.JTextField();
        jLblTextoPedirContraseña = new javax.swing.JLabel();
        jLblTextoPedirNombre = new javax.swing.JLabel();
        jTxtFldNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Personaje");
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jBttnCrearPersonaje.setBackground(new java.awt.Color(255, 153, 0));
        jBttnCrearPersonaje.setForeground(new java.awt.Color(0, 0, 0));
        jBttnCrearPersonaje.setText("Crear Personaje");
        jBttnCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCrearPersonajeActionPerformed(evt);
            }
        });

        jTxtFldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldContraseñaActionPerformed(evt);
            }
        });

        jLblTextoPedirContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLblTextoPedirContraseña.setText("Cree una contraseña");

        jLblTextoPedirNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblTextoPedirNombre.setText("Ingrese su nombre de Jugador");

        jTxtFldNombre.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblTextoPedirNombre)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtFldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jBttnCrearPersonaje))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jLblTextoPedirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLblTextoPedirNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTextoPedirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBttnCrearPersonaje)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldContraseñaActionPerformed

    private void jBttnCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCrearPersonajeActionPerformed
        
        contraseña = null;
        
        try {
            this.setVisible(false);
            contraseña = jTxtFldContraseña.getText();
            nombre = jTxtFldNombre.getText();
            AdminJuego.inicarCarpetaYValidarContraseña(contraseña);
            Jugador jugador = new Jugador(contraseña, nombre, ventana);
            AdminJuego.guardar(jugador);
            super.hide();
       
        } catch (JuegoPokemonException e) {
                
                contraseña = null;
                jTxtFldContraseña.setText("");
                jTxtFldNombre.setText("");
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                this.setVisible(true);
               // e.printStackTrace();
        }
    }//GEN-LAST:event_jBttnCrearPersonajeActionPerformed

    public String getContraseña (){
        return contraseña;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnCrearPersonaje;
    private javax.swing.JLabel jLblTextoPedirContraseña;
    private javax.swing.JLabel jLblTextoPedirNombre;
    private javax.swing.JTextField jTxtFldContraseña;
    private javax.swing.JTextField jTxtFldNombre;
    // End of variables declaration//GEN-END:variables
}
