/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ipc12023.juegopokemon_proyecto2.frontend;

import ipc12023.juegopokemon_proyecto2.frontend.Batalla.JInternalFrameBatalla;
import ipc12023.juegopokemon_proyecto2.backend.*;
import ipc12023.juegopokemon_proyecto2.frontend.CasillaMapa.JLblCasillaMapa;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public final class JuegoPokemonApp extends javax.swing.JFrame {

    private String contraseña ;
    private Mapa mapa;
    private Mapa mapaAnterior;
    private boolean enBatalla;
    
    public JuegoPokemonApp() {
        initComponents(); 
        redimensionarPanel(9);
        mostrarComponentesTablero(false);
        super.setLocation(350, 50);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jBttnSalir = new javax.swing.JButton();
        jPnlTablero = new javax.swing.JPanel();
        jPnlInstruccionesMovimiento = new javax.swing.JPanel();
        jTxtFldLeerOpcionMovimiento = new javax.swing.JTextField();
        jLblPedirMovimientoTexto2 = new javax.swing.JLabel();
        jLblPedirMovimientoTexto1 = new javax.swing.JLabel();
        jPnlImagenesMovimiento = new javax.swing.JPanel();
        jLblImagenIzquierda = new javax.swing.JLabel();
        jLblImagenAbajo = new javax.swing.JLabel();
        jLblImagenArriba = new javax.swing.JLabel();
        jLblImagenIzquierda1 = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        flMnJuego = new javax.swing.JMenu();
        jMnNuevoJuego = new javax.swing.JMenu();
        jMnItmPersonaje = new javax.swing.JMenuItem();
        jSprtrNuevoJuego = new javax.swing.JPopupMenu.Separator();
        jMnItmCargarPersonaje = new javax.swing.JMenuItem();
        jSprtrJuego1 = new javax.swing.JPopupMenu.Separator();
        jMnItmTerminarPartida = new javax.swing.JMenuItem();
        jSprtrJuego2 = new javax.swing.JPopupMenu.Separator();
        jMntmSalir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Pokemon RPG");
        setAutoRequestFocus(false);

        desktopPane.setBackground(new java.awt.Color(153, 153, 255));
        desktopPane.setBorder(new javax.swing.border.MatteBorder(null));
        desktopPane.setToolTipText("");
        desktopPane.setPreferredSize(new java.awt.Dimension(600, 700));

        jBttnSalir.setBackground(new java.awt.Color(255, 153, 0));
        jBttnSalir.setForeground(new java.awt.Color(0, 0, 0));
        jBttnSalir.setText("SALIR DEL MAPA");
        jBttnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSalirActionPerformed(evt);
            }
        });

        jPnlTablero.setBackground(new java.awt.Color(204, 255, 204));
        jPnlTablero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPnlTablero.setPreferredSize(new java.awt.Dimension(460, 460));
        jPnlTablero.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPnlTableroLayout = new javax.swing.GroupLayout(jPnlTablero);
        jPnlTablero.setLayout(jPnlTableroLayout);
        jPnlTableroLayout.setHorizontalGroup(
            jPnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPnlTableroLayout.setVerticalGroup(
            jPnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPnlInstruccionesMovimiento.setBackground(new java.awt.Color(204, 204, 255));
        jPnlInstruccionesMovimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTxtFldLeerOpcionMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldLeerOpcionMovimientoActionPerformed(evt);
            }
        });

        jLblPedirMovimientoTexto2.setBackground(new java.awt.Color(0, 0, 0));
        jLblPedirMovimientoTexto2.setForeground(new java.awt.Color(0, 0, 0));
        jLblPedirMovimientoTexto2.setText("Y PRESIONE ENTER PARA MOVERSE");

        jLblPedirMovimientoTexto1.setBackground(new java.awt.Color(0, 0, 0));
        jLblPedirMovimientoTexto1.setForeground(new java.awt.Color(0, 0, 0));
        jLblPedirMovimientoTexto1.setText("INGRESE UNA OPCION");

        javax.swing.GroupLayout jPnlInstruccionesMovimientoLayout = new javax.swing.GroupLayout(jPnlInstruccionesMovimiento);
        jPnlInstruccionesMovimiento.setLayout(jPnlInstruccionesMovimientoLayout);
        jPnlInstruccionesMovimientoLayout.setHorizontalGroup(
            jPnlInstruccionesMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlInstruccionesMovimientoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTxtFldLeerOpcionMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlInstruccionesMovimientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblPedirMovimientoTexto2)
                .addGap(15, 15, 15))
            .addGroup(jPnlInstruccionesMovimientoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLblPedirMovimientoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlInstruccionesMovimientoLayout.setVerticalGroup(
            jPnlInstruccionesMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlInstruccionesMovimientoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLblPedirMovimientoTexto1)
                .addGap(6, 6, 6)
                .addComponent(jLblPedirMovimientoTexto2)
                .addGap(6, 6, 6)
                .addComponent(jTxtFldLeerOpcionMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPnlImagenesMovimiento.setBackground(new java.awt.Color(204, 204, 255));
        jPnlImagenesMovimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblImagenIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/izquierda.png"))); // NOI18N

        jLblImagenAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/abajo.png"))); // NOI18N

        jLblImagenArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arriba.png"))); // NOI18N

        jLblImagenIzquierda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/derecha.png"))); // NOI18N

        javax.swing.GroupLayout jPnlImagenesMovimientoLayout = new javax.swing.GroupLayout(jPnlImagenesMovimiento);
        jPnlImagenesMovimiento.setLayout(jPnlImagenesMovimientoLayout);
        jPnlImagenesMovimientoLayout.setHorizontalGroup(
            jPnlImagenesMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlImagenesMovimientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblImagenIzquierda)
                .addGap(6, 6, 6)
                .addGroup(jPnlImagenesMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblImagenArriba)
                    .addComponent(jLblImagenAbajo))
                .addGap(6, 6, 6)
                .addComponent(jLblImagenIzquierda1)
                .addContainerGap())
        );
        jPnlImagenesMovimientoLayout.setVerticalGroup(
            jPnlImagenesMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlImagenesMovimientoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLblImagenIzquierda))
            .addGroup(jPnlImagenesMovimientoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLblImagenArriba)
                .addGap(18, 18, 18)
                .addComponent(jLblImagenAbajo))
            .addGroup(jPnlImagenesMovimientoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLblImagenIzquierda1))
        );

        desktopPane.setLayer(jBttnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPnlTablero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPnlInstruccionesMovimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPnlImagenesMovimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(jPnlImagenesMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jBttnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPnlInstruccionesMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(jPnlInstruccionesMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBttnSalir))
                    .addComponent(jPnlImagenesMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jPnlTablero.getAccessibleContext().setAccessibleDescription("");

        menuBarPrincipal.setBackground(new java.awt.Color(255, 153, 0));
        menuBarPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        flMnJuego.setMnemonic('f');
        flMnJuego.setText("Juego");

        jMnNuevoJuego.setText("NuevoJuego");

        jMnItmPersonaje.setText("Personaje");
        jMnItmPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnItmPersonajeActionPerformed(evt);
            }
        });
        jMnNuevoJuego.add(jMnItmPersonaje);
        jMnNuevoJuego.add(jSprtrNuevoJuego);

        jMnItmCargarPersonaje.setText("CargarPersonaje");
        jMnItmCargarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnItmCargarPersonajeActionPerformed(evt);
            }
        });
        jMnNuevoJuego.add(jMnItmCargarPersonaje);

        flMnJuego.add(jMnNuevoJuego);
        flMnJuego.add(jSprtrJuego1);

        jMnItmTerminarPartida.setText("Terminar Partida");
        jMnItmTerminarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnItmTerminarPartidaActionPerformed(evt);
            }
        });
        flMnJuego.add(jMnItmTerminarPartida);
        flMnJuego.add(jSprtrJuego2);

        jMntmSalir.setMnemonic('a');
        jMntmSalir.setText("Salir");
        jMntmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntmSalirActionPerformed(evt);
            }
        });
        flMnJuego.add(jMntmSalir);

        menuBarPrincipal.add(flMnJuego);

        menuReportes.setMnemonic('e');
        menuReportes.setText("Mas...");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Reportes");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menuReportes.add(cutMenuItem);

        menuBarPrincipal.add(menuReportes);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSalirActionPerformed
       
        regresarMapaPrincipal();
        refrescar();
    }//GEN-LAST:event_jBttnSalirActionPerformed

    private void jTxtFldLeerOpcionMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldLeerOpcionMovimientoActionPerformed

        mapa.moverPieza(jTxtFldLeerOpcionMovimiento.getText());
        jTxtFldLeerOpcionMovimiento.setText("");
        refrescar();
    }//GEN-LAST:event_jTxtFldLeerOpcionMovimientoActionPerformed

    private void jMntmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntmSalirActionPerformed
        this.reiniciar();
        System.exit(0);
    }//GEN-LAST:event_jMntmSalirActionPerformed

    private void jMnItmPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnItmPersonajeActionPerformed
        
        reiniciar();
        JDialogNuevoPersonaje nuevoPersonaje = new JDialogNuevoPersonaje(this, true,this);
        nuevoPersonaje.setVisible(true);
        contraseña = nuevoPersonaje.getContraseña();
        
        if ( contraseña != null) {
            
            try {
                nuevoPersonaje.dispose();
                mapa = new MapaModoHistoria(contraseña, this);
                mapaAnterior = mapa;
                refrescar();
                AdminJuego.cargar(contraseña).setMapa(mapa);
            } catch (JuegoPokemonException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROE", JOptionPane.ERROR_MESSAGE);
                reiniciar();
            }
            
        }
        else {
           nuevoPersonaje.dispose();
        }
        

    }//GEN-LAST:event_jMnItmPersonajeActionPerformed

    private void jMnItmCargarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnItmCargarPersonajeActionPerformed
        
        reiniciar();
        JDialogCargarPersonaje cargar = new JDialogCargarPersonaje( this, true);
        cargar.setVisible(true);
        contraseña = cargar.getContraseña();
        
        if (contraseña != null) {
                mapa = new MapaModoHistoria(contraseña, this);
                mapaAnterior = mapa;
                refrescar();
                cargar.dispose();
        }
        else{
            cargar.dispose();
        }
        
        
        
    }//GEN-LAST:event_jMnItmCargarPersonajeActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        try {
            JDlgReportes reportes = new JDlgReportes(this, rootPaneCheckingEnabled, AdminJuego.cargar(contraseña));
            reportes.setVisible(true);
        } catch (JuegoPokemonException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMnItmTerminarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnItmTerminarPartidaActionPerformed
        
        if (mapaAnterior == null) {
            reiniciar();
        } else{
            
             if (enBatalla) {

                JOptionPane.showMessageDialog(this, "Debes salir de la batalla primero", "No se puede guardar la partida", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                reiniciar();
            }
        }
        
        
    }//GEN-LAST:event_jMnItmTerminarPartidaActionPerformed

    public void setTableroAnterior(Mapa tableroAnterior){
        this.mapaAnterior = tableroAnterior;
    }
    
    public void ocultarBttnSalir (){
        jBttnSalir.setVisible(false);
    }
    
    public void mostrarBttnSalir (){
        jBttnSalir.setVisible(true);
    }
    
    public void agregarGridLayaut(int tamaño){
        
        jPnlTablero.setLayout(new GridLayout(tamaño, tamaño));
     }
    
    public void refrescar (){
        
        JLblCasillaMapa[][] mapavisible = mapa.getMapaVisible();
        
        jPnlTablero.removeAll();
        jPnlTablero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, mapa.getNombre(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPnlTablero.setBackground(new java.awt.Color(204, 255, 204));

        for (int i = 0; i < mapavisible.length; i++) {
            for (int j = 0; j < mapavisible.length; j++) {
                
               jPnlTablero.add(mapavisible[i][j]);   
            }    
        }
        
        jPnlTablero.repaint();
        jPnlTablero.revalidate();
       
    }
    
    public void mostrarComponentesTablero(boolean valor){
        
        jPnlTablero.setVisible(valor);
        jPnlImagenesMovimiento.setVisible(valor);
        jPnlInstruccionesMovimiento.setVisible(valor);
        jBttnSalir.setVisible(valor);
        
        enBatalla = !valor;
        
        
    }
    
    public void setMapa(Mapa mapa){
        this.mapa = mapa;
    } 
    
    public void setMapaAnterior(Mapa mapaAnterior){
        this.mapaAnterior = mapaAnterior;
    }
    
    private void reiniciar(){
        
        try {
            mapa = null;
            mapaAnterior = null;
            contraseña = null;
            mostrarComponentesTablero(false);
        } catch (NullPointerException e) {
                
        }
    }
    
    public void addJFrameComponent (JInternalFrame frame){
        
       this.desktopPane.add(((JInternalFrameBatalla)frame));
       mostrarComponentesTablero(false);
    }
    
    public void regresarMapaPrincipal(){
        mapa = mapaAnterior;
        agregarGridLayaut(mapa.getTamaño());
        jBttnSalir.setVisible(false);
    }
    
    public void redimensionarPanel( int tamaño){
        int size = (tamaño * 50) + (tamaño + 1); 
        
        jPnlTablero.resize(new Dimension(size, size));
    }
    
    public String getContraseña(){
        return contraseña;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu flMnJuego;
    private javax.swing.JButton jBttnSalir;
    private javax.swing.JLabel jLblImagenAbajo;
    private javax.swing.JLabel jLblImagenArriba;
    private javax.swing.JLabel jLblImagenIzquierda;
    private javax.swing.JLabel jLblImagenIzquierda1;
    private javax.swing.JLabel jLblPedirMovimientoTexto1;
    private javax.swing.JLabel jLblPedirMovimientoTexto2;
    private javax.swing.JMenuItem jMnItmCargarPersonaje;
    private javax.swing.JMenuItem jMnItmPersonaje;
    private javax.swing.JMenuItem jMnItmTerminarPartida;
    private javax.swing.JMenu jMnNuevoJuego;
    private javax.swing.JMenuItem jMntmSalir;
    private javax.swing.JPanel jPnlImagenesMovimiento;
    private javax.swing.JPanel jPnlInstruccionesMovimiento;
    protected javax.swing.JPanel jPnlTablero;
    private javax.swing.JPopupMenu.Separator jSprtrJuego1;
    private javax.swing.JPopupMenu.Separator jSprtrJuego2;
    private javax.swing.JPopupMenu.Separator jSprtrNuevoJuego;
    private javax.swing.JTextField jTxtFldLeerOpcionMovimiento;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables

}
